import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import categoryRoutes from './category.routes';
import unitRoutes from './unit.routes';
import supplierRoutes from './supplier.routes';
import warehouseRoutes from './warehouse.routes';
import productRoutes from './product.routes';
import purchaseRoutes from './purchase.routes';
import stockRoutes from './stock.routes';
import inventoryRoutes from './inventory.routes';
import stockMovementRoutes from './stockMovement.routes';
import wastageRoutes from './wastage.routes';
import recipeRoutes from './recipe.routes';
import menuRoutes from './menu.routes';
import saleRoutes from './sale.routes';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import reportsRoutes from './reports.routes';
import auditLogRoutes from './auditLog.routes';
import dashboardRoutes from './dashboard.routes';
import publicRoutes from './public.routes';
import orderRoutes from './order.routes';
import expenseRoutes from './expense.routes';
import productionRoutes from './production.routes';

const router = Router();

router.use('/public', publicRoutes);
router.use('/orders', orderRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/categories', categoryRoutes);
router.use('/units', unitRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/products', productRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/stock', stockRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/stock-movements', stockMovementRoutes);
router.use('/wastage', wastageRoutes);
router.use('/recipes', recipeRoutes);
router.use('/menu', menuRoutes);
router.use('/sales', saleRoutes);
router.use('/expenses', expenseRoutes);
router.use('/production', productionRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/reports', reportsRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/dashboard', dashboardRoutes);

export default router;
